### ISSUE TITLE
Delete the commit that introduced target folder

### ISSUE THREAD

**Issue by flyingcakes85** [codic12/worm#2]
https://github.com/codic12/worm/commit/13cbcf96b8de25eb77db6e8e1e03c83f20a8697a

You can use an interactive rebase to remove target folder from repo.

Or use the following command in project root.
```sh
git filter-branch --tree-filter 'rm -f target' HEAD
```
Do note that this will change commit hashes and you'll need to force push once ( `git push -f` ), but I don't see much issue in that since there aren't any public forks.

Requesting this since the target files are still in git history and that pulls up the size when cloning.

**Comment by codic12** [comment]
Thanks, fixed

also recognize you from the eos forums ;)

**Comment by codic12** [comment]
Actually, hmm, looks like it's still in history...

**Comment by flyingcakes85** [comment]
> Actually, hmm, looks like it's still in history...

Let me check

**Comment by codic12** [comment]
I also tried using git filter-repo; either way when I try to push it just says "everything up-to-date"

**Comment by flyingcakes85** [comment]
@codic12 
https://github.com/codic12/worm/commit/daaa2809c19d335db739fb45f10b6029c2ab971a
Files have indeed been removed. The commit is there, but its got readme changes, not target :+1: 

https://github.com/codic12/worm/commit/f04c0cf530f82ad4cef7884320f32c2869bbaaac - this commit has become empty, since there is no target folder to remove in the first place now. You could do `git rebase -i HEAD~3`. In the file that opens, replace `pick` with `d` before the commit title. That will remove the commit message altogether.

**Comment by codic12** [comment]
Great, thanks!

**Comment by flyingcakes85** [comment]
Issue can be closed.
