### ISSUE TITLE
worm binary dlopens non existing .so files

### ISSUE THREAD

**Issue by fdziarmagowski** [codic12/worm#47]
The problem occurs on a host system, where _-devel_ packages are not present
```
libX11.so: cannot open shared object file: No such file or directory
libX11.so: cannot open shared object file: No such file or directory
libXft.so: cannot open shared object file: No such file or directory
could not load: libXft.so
```
Must be an internal thing, as the binary is not linked against x11 or xft:
```
ldd ./worm
	linux-vdso.so.1 (0x00007ffc0a31e000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f05d1508000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f05d14fd000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f05d14f7000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f05d1331000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f05d1761000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f05d1310000)
```
Not using any preinstalled packages here:
```
  Verifying dependencies for worm@0.1.0
    Prompt: No local packages.json found, download it from internet? -> [forced yes]
```
This might work on Arch, where .so are part of a main package, but no other distribution will allow to run _worm_ without installing tons of _-devel_ packages.
The binary was built using nim 1.6.0

**Comment by codic12** [comment]
> This might work on Arch, where .so are part of a main package, but no other distribution will allow to run worm without installing tons of -devel packages.

No, all you need is the development packages for X11 and Xft, eg on debian libx11-dev/libxft-dev. Nim's X11 bindings dynamically load the libraries at runtime for some reason, therefore you need the development packages.

Thanks for trying out worm! (and sorry for the late reply). If installing development packages of X11/Xft fixes your issue, please feel free to close it.

**Comment by fdziarmagowski** [comment]
This is not a correct solution, despite it will worm working. These are files required at build time not at runtime. Nim is doing sth very strange here. But if this is a Nim problem, this should not be assigned to your project. 
Closing & thanks for creating worm!

**Comment by codic12** [comment]
> These are files required at build time not at runtime.

No, they are required at runtime because the Nim X11 wrapper dynamically loads the library at runtime (see https://github.com/nim-lang/x11/blob/master/x11/x11pragma.nim). It seems you can change it to load statically with use_pkg_config_static option, so I might experiment with that.
