### ISSUE TITLE
BadAccess

### ISSUE THREAD

**Issue by LotfiAghel** [codic12/worm#74]
18:38:31 | INFO | wm.nim:35 | Opened display
X Error of failed request:  BadAccess (attempt to access private resource denied)
  Major opcode of failed request:  2 (X_ChangeWindowAttributes)
  Serial number of failed request:  23
  Current serial number in output stream:  24

**Comment by codic12** [comment]
Not an issue, it's because you're trying to run worm on top of another window manager. You have to start it in xinitrc or similar, or use a display manager.
