### ISSUE TITLE
Polybar error collects issues 

### ISSUE THREAD

**Issue by nixfreak** [codic12/worm#75]
If you're installing polybar using aur.archlinux.org packages make sure to install requests version 2.27.1 using pip install requests==2.27.1 otherwise polybar will fail to build. 

Also nim c isn't recognized when using git build. make sure to use choosenim update stable , and or choosenim update devel.

**Comment by codic12** [comment]
The polybar issue worm can't do anything about, please report it here: https://aur.archlinux.org/packages/polybar

> Also nim c isn't recognized when using git build. make sure to use choosenim update stable , and or choosenim update devel.

Choosenim should prompt you the first time you run the installer to install a Nim compiler.
