### ISSUE TITLE
unfloat 

### ISSUE THREAD

**Issue by nixfreak** [codic12/worm#78]
When I tried to take a float object (window) I can't make it static again 

I'm sure its a user error. 

here is my sxhkdrc file. 

# Restart worm
super + ctrl + r
	worm

# Open terminal kitty
super + Return
    kitty

#ctrl + space
#   ulauncher &

super + d
    ulauncher &

super + b
    brave &

# Quit worm
ctrl + alt + q
	pkill worm

# Close app
super + q
	wormc close-active-client

# Maximize app
super + f
	wormc maximize-active-client

# Minimize app
super + h
	wormc minimize-active-client

# Tags
super + {_, shift + } {1-9}
	wormc {switch,move-active}-tag {1-9}

# Set master windows
super + m
	wormc master-active

# Float a window
super + shift + space
	wormc float-active

**Comment by codic12** [comment]
> When I tried to take a float object (window) I can't make it static again
Do you mean putting a floating window back into tiling? In that case I realized I never implemented that. I just made float-active toggle now. https://github.com/codic12/worm/commit/ffbb81023ad2988611b8d082d6558eec998d4f93

**Comment by nixfreak** [comment]
So it kind of works... I am appreciated though , thank you. 

The event to "unfloat" a window won't work until you close the window and re-open it. 
swaywm is kind of like this to. 

So if I have a window open and I enable float on it it pops out , but if I call float again , nothing happens. If I close the window and re-open then it goes back to unfloat. If I open a window and call float then close that window and call the window then that window will still be active float. 

Is that a way to launch an application using float ? So if I call an application say ulauncher or app_launcher from owlkettle. Can I by default when that keybinding is set to open a specific application , can that application we launched as a float?

**Comment by codic12** [comment]
> Is that a way to launch an application using float ? So if I call an application say ulauncher or app_launcher from owlkettle. Can I by default when that keybinding is set to open a specific application , can that application we launched as a float? Also restarted worm doesn't work with super + ctrl + r

It doesn't run with super + ctrl + r and I'm not sure why that keybinding is in the example, I will add a proper restart command to worm soon. To launch an application as floating, you can in the future use window rules, for now you could just bind the key binding to your application + tile.

> So if I have a window open and I enable float on it it pops out , but if I call float again , nothing happens. If I close the window and re-open then it goes back to unfloat. If I open a window and call float then close that window and call the window then that window will still be active float.

Are you sure you are using master or am I misunderstanding something? Can you send a video? It works for me...

https://user-images.githubusercontent.com/48339289/167273332-9cb3cc2a-9ead-4558-84c0-7cb07c372a5f.mp4

**Comment by nixfreak** [comment]
Sorry the video is messed up , first time playing with this software. 


https://user-images.githubusercontent.com/3707258/167312779-0b9026cc-21b4-4dc2-9fca-f1f6b2b72365.mp4

**Comment by nixfreak** [comment]
Sorry about the video , new software never really used it before

**Comment by codic12** [comment]
What is Super+Shift+Space bound to? Can you send your rc?

I think the only possible issue is that you might not be using the latest master for some reason:
 - worm from AUR is the stable version
 - worm-git you need to recompile with your aur helper, it won't do it automatically
 - if from src yourself you must git pull

**Comment by nixfreak** [comment]
Yeah I did a get pull , even rebuild the binaries with nimble again. 

`#!/usr/bin/env bash
# | NOTE | NOTE | NOTE | NOTE |
# if you use this configuration, make sure that the paths are all right for the configuration file. this is just an example!!!
# you would also need things like nitrogen and polybar installed.
exec nitrogen --restore &

exec polybar  -q -c ~/.config/worm/polybar/config.ini &

exec mpd &

exec sxhkd -c ~/.config/worm/sxhkdrc &

wormc border-width 6

## pywal support
# # CONFIGURE
# pywal_active_index="3" # color3
# pywal_inactive_index="4" # color4
#
# # CODE
# contrast_text_for () {
#   # Formula from:
#   # https://stackoverflow.com/questions/596216/formula-to-determine-perceived-brightness-of-rgb-color
#   # https://www.w3.org/TR/AERT/#color-contrast
#   if perl -e "exit ((1 - (0.299 * $((16#${1:0:2})) + 0.587 * $((16#${1:2:2})) + 0.114 * $((16#${1:4:2}))) / 255) > 0.5)"; then
#     echo $((16#FF000000))
#   else
#     echo $((16#FFFFFFFF))
#   fi
# }
# pywal_active="$(sed -n $(($pywal_active_index + 1))p ~/.cache/wal/colors | tail -c +2)"
# pywal_inactive="$(sed -n $(($pywal_inactive_index + 1))p ~/.cache/wal/colors | tail -c +2)"
# wormc border-active-pixel $((16#FF$pywal_active))
# wormc border-inactive-pixel $((16#FF$pywal_inactive))
# wormc frame-active-pixel $((16#FF$pywal_active))
# wormc frame-inactive-pixel $((16#FF$pywal_inactive))
# wormc text-active-pixel $(contrast_text_for $pywal_active)
# wormc text-inactive-pixel $(contrast_text_for $pywal_inactive)

wormc layout tiling
wormc struts 75 20 20 20
wormc gaps 20
wormc frame-height 0`

**Comment by codic12** [comment]
If you copied /usr/bin/worm and /usr/bin/wormc did you remember to update both?  If so, then I have no idea what the issue is... I can't reproduce it.

**Comment by codic12** [comment]
No problem!
