### ISSUE TITLE
bspc rule -a

### ISSUE THREAD

**Issue by yadex** [codic12/worm#81]
Can worm add rules for each app like “bspc rule -a”？

**Comment by codic12** [comment]
Yes, it has a rudimentary form of window rules, feel free to ask if you need help as the docs really do need some love. :)

However, right now I believe it lets you only disable decorations. See docs for decoration-disable(string regex).

**Comment by is0n** [comment]
What rules do you plan on setting @yadex?

For example, if you wanted Firefox to always be in workspace two, you could use the following:
```shell
xprop -spy -root _NET_CLIENT_LIST | while read; do
  xdotool search --class firefox exec wormc move-active-tag 2
done
```
