### ISSUE TITLE
[Bug] `focus-mode` does not work.

### ISSUE THREAD

**Issue by 2brownc** [codic12/worm#85]
**Documented Behaviour:**
[`focus-mode(int)`](https://github.com/codic12/worm/blob/main/docs/wormc.md#focus-modeint)` : Sets the focus mode. 1: is focus-follows-click (like Microsoft Windows). 2: is the traditional X11 focus-follows-mouse.

**Observed Behaviour:**
`wormc focus-mode 2` does not result in activation/focus of inactive client on mouse hover. The same situation is observed in both tile and float modes.

**Comment by codic12** [comment]
very delayed reply :) but it works for me, are you sure you weren't using an older version ?

**Comment by 2brownc** [comment]
Hi. Better late than never. :)

I am afraid I can't confirm if it's working now because I am currently using another WM. 

I installed the official Endeavour OS version of Worm WM. So I think it is the latest version. And I assure you, at the time of me posting this issue, it is NOT working.

**Comment by codic12** [comment]
oh I see, it's because I forgot that I haven't tagged a new release, and endeavourOS uses the stable version, which doesn't have focus-mode. a silly mistake, I will be sure to tag a new release soon :)

**Comment by codic12** [comment]
fixed!
